"""add category to expense

Revision ID: c207d5e3f987
Revises: dd863f65f4d6
Create Date: 2026-02-01 22:21:52.402006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c207d5e3f987'
down_revision = 'dd863f65f4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('monthly_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'month', name='uq_budget_user_cat_month')
    )
    with op.batch_alter_table('monthly_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_budgets_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_budgets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_category_id'))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('monthly_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_budgets_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_budgets_category_id'))

    op.drop_table('monthly_budgets')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
